#! /usr/bin/env python3

import psycopg2
import sys
import datetime #This is the reason I'm upset.  This right here.

def main():
        con = psycopg2.connect(dbname = sys.argv[1])

        cur = con.cursor()

        print("What would you like to see?\n")
        print("1. Longest Fight Time?")
        print("2. Shortest Fight Time?")
        print("3. Most expansive list of attacks?")
        print("4. Most Wins?")
        print("5. Most Losses?")
        print("6. Most Draws?")
        choice = input("")
        
        cur.execute("select * from fight")
        fightfacts = cur.fetchall()
        
        cur.execute("select * from combatant")
        combatantinfo = cur.fetchall()


        num = 0
        for item in combatantinfo:
            if int(item[0]) > num:
                num = int(item[0])

        listTimeIn = [45]
        if ( choice < '3' ):
            for x in range(0, num):
                timeIn = 0
                for each in fightfacts:
                    if (each[0] == x + 1) or (each[1] == x + 1):
                        timeIn += (int(each[4].minute)*60+int(each[4].second)
                        - int(each[3].minute)*60+int(each[3].second))
                listTimeIn.append(timeIn)
        
            if choice == '1':
                LongestFighter = max(listTimeIn)
                x = [i for i, j in enumerate(listTimeIn) if j == LongestFighter]

                for each in combatantinfo:
                    if (each[0] == x[0]):
                        print(each[1], "fought for",LongestFighter,"seconds!")

            elif choice == '2':
                ShortestFighter = min(listTimeIn)
                x = [i for i, j in enumerate(listTimeIn) if j==ShortestFighter]

                for each in combatantinfo:
                    if (each[0] == x[0]):
                        print(each[1],"fought for",ShortestFighter,"seconds!")
                    if (x[1]):
                        if (each[0] == x[1]):
                            print(each[1],"fought for",ShortestFighter,"seconds!")
        elif ( choice == '3' ):
            pass
        elif ( choice == '4' ):
            pass
        elif ( choice == '5' ):
            pass
        elif ( choice == '6' ):
            pass


#Prompt for input;  "What do you want to see?"
#1. Fight time:  Longest / Shortest
#2. Win Rate:  Highest / Lowest
#3. Most attacks
#4. Wins / Losses / Draws by Species

if __name__ == '__main__':
    main()
